wla-6801 sdump.a01
echo [objects]>linkfile
echo sdump.o>>linkfile
wlalink.exe -s -r -v linkfile sdump.bin
bin2srec -s -o -0xA000 sdump.bin > sdump.s19
copy /b sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin sdump512.bin
copy /b sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin+sdump.bin sdump256.bin
copy /b mtrak_keyer_dump_a.bin+BYTE_PGM.bin sprog.bin
copy /b sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin+sprog.bin sprog256.bin
